version: 0.1

phases:
  build:
    commands:
      - npm install
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - images/dns.png
    - images/iot.png
    - images/XSighting.png
    - styles/main.css
    - dist/bundle.js