version: 0.1

phases:
  build:
    commands:
      - npm install
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - images/example1.png
    - images/example2.png
    - images/example3.png
    - styles/main.css
    - dist/bundle.js